// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Medium : MonoBehaviour, DifficultyStrategy
{

	public Medium ()
	{
	}

	public void instantiate() {
		EnemyAttack._setAttackDamage (10);
		PlayerShooting._setDamagePerShot (15);
	}

	public void calculateScore() {
			Debug.Log("Medium : " + gameObject.GetComponent<EnemyHealth> ().tag);
			if (gameObject.GetComponent<EnemyHealth> ().tag == "Zombunny") {
				// gameObject.GetComponent<EnemyHealth> ().scoreValue -= 3;
				ScoreManager.score += (gameObject.GetComponent<EnemyHealth> ().scoreValue - 3);
			} 
			if (gameObject.GetComponent<EnemyHealth> ().tag == "Zombear") {
				//gameObject.GetComponent<EnemyHealth> ().scoreValue -= 3;
				ScoreManager.score += (gameObject.GetComponent<EnemyHealth> ().scoreValue - 3);
			}
			if (gameObject.GetComponent<EnemyHealth> ().tag == "Hellephant") {
				//gameObject.GetComponent<EnemyHealth> ().scoreValue -= 5;
				ScoreManager.score += (gameObject.GetComponent<EnemyHealth> ().scoreValue - 5);
			} 
	}

    public  int getTarget()
    {
        return 50;
    }
    public string[] getNumbersForAddition()
    {
        string[] array = { "5", "6", "7", "-9", "8", "9", "-17", "15"};
        return array;
    }
    public int getWinningScore()
    {
        return 100;
    }
}